#!/command/with-contenv bash

source /assets/functions/00-container
set -a
prepare_service
set +a
PROCESS_NAME="z2m"

cat <<EOF
*******************************************************************************
*                                                                             *
*                    END OF LIFE NOTICE AUGUST 18, 2025                       *
*                               tiredofit/z2m                                 *
*                                                                             *
* This image is no longer maintained as of and will not receive updates.      *
*                                                                             *
* A successor image is available at:                                          *
*                                                                             *
* Repository | Documentation:                                                 *
*   - https://github.com/nfrastack/container-z2m                              *
*                                                                             *
* Image Registries:                                                           *
*   - https://hub.docker.com/r/nfrastack/z2m                                  *
*   - https://github.com/nfrastack/container-z2m/pkgs/container/container-z2m *
*                                                                             *
* Please visit https://nfrastack.com for more information.                    *
*                                                                             *
*******************************************************************************

EOF

sleep 15

bootstrap_filesystem
generate_config
configure_proxy

liftoff
