services:
  z2m-app:
    image: tiredofit/z2m:latest
    container_name: z2m-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.z2m.rule=Host(`z2m.example.com`)
      - traefik.http.services.z2m.loadbalancer.server.port=8080
    #ports:
      #- 8080:8080
    volumes:
      - ./data/z2m:/data
      - ./logs/z2m:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=z2m-app
      - SETUP_MODE=AUTO

      - MQTT_HOST=mqtt://mqtt
      - MQTT_USER=mosquitto
      - MQTT_PASS=secure

      - ADAPTER_LOCATION=tcp://zigbee-adapter:6638

      - ENABLE_DEVICE_AVAILABILITY=false

      - ENABLE_FRONTEND=true
      - FRONTEND_LISTEN_PORT=8080

      - ENABLE_OTA=false

      - ZIGBEE_CHANNEL=25
      - ZIGBEE_TRANSMIT_POWER=20
    networks:
      - proxy
      - services
    restart: always

  mqtt-app:
    image: tiredofit/mosquitto:latest
    container_name: mqtt-app
    #ports:
      #- 1883:1883
    volumes:
      #- ./config:/config
      - ./data/mqtt:/data
      - ./logs/mosquitto:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=mqtt-app

      - LISTEN_PORT=1883

      - LOG_LEVEL=all
      - LOG_TYPE=console,file

      - CREDENTIAL01_USER=mosquitto
      - CREDENTIAL01_PASS=secure

      - ENABLE_PERSISTENCE=TRUE
    networks:
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
