services:
  z2m-app:
    image: tiredofit/z2m:latest
    container_name: z2m-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.z2m.rule=Host(`z2m.example.com`)
      - traefik.http.services.z2m.loadbalancer.server.port=8080
    volumes:
      - ./data:/data
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=z2m-app
      - SETUP_MODE=AUTO

      - MQTT_HOST=mqtt://mqtt

      - ADAPTER_LOCATION=tcp://zigbee-adapter:6638

      - ENABLE_DEVICE_AVAILABILITY=false

      - ENABLE_FRONTEND=true
      - FRONTEND_LISTEN_PORT=8080

      - ENABLE_OTA=false

      - ZIGBEE_CHANNEL=25
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
